repo:
  - name: io.peasoup.inv.pub.tools.kubernetes
    path: tools/kubernetes
    src: https://github.com/peasoupio/inv-repo.git

    hooks:
      init: |
        git clone --depth 1 --no-checkout ${src} .
        git checkout master -- ${path}

      pull: |
        git pull
